"use client";
import { useEffect, useState } from 'react';
import type { LibraryAsset } from '../../../src/studio/asset-library';
import type { StoredProject } from '../../../src/studio/project-store';
import { parseAssetBindings } from '../../../src/studio/asset-bindings';
import './library.css';

const kinds:Record<string,string>={maps:'맵',scenes:'장면 배경',portraits:'초상',sprites:'전투 캐릭터·스킨', motions:'시나리오 캐릭터',items:'아이템',objects:'지형지물',fx:'공격·책략 효과',bgm:'배경음악',sfx:'효과음'};
async function api<T>(path:string,init?:RequestInit):Promise<T>{const r=await fetch('/api/studio/'+path,{cache:'no-store',...init});const data=await r.json();if(!r.ok)throw new Error(data.error??'요청 실패');return data as T;}
const url=(p:string)=>(p.startsWith('/assets/library/')?p.replace('/assets/','/api/local-assets/'):p).split('/').map(encodeURIComponent).join('/');
function Preview({asset}:{asset:LibraryAsset}) { return asset.kind==='bgm'||asset.kind==='sfx'?<audio controls preload="none" src={url(asset.preview)}/>:<img loading="lazy" src={url(asset.preview)} alt={asset.name}/>; }
export default function AssetLibrary(){
  const [limit,setLimit]=useState(120),[scope,setScope]=useState('all'),[assets,setAssets]=useState<LibraryAsset[]>([]),[project,setProject]=useState<StoredProject|null>(null),[kind,setKind]=useState('portraits'),[query,setQuery]=useState(''),[selected,setSelected]=useState<LibraryAsset|null>(null),[target,setTarget]=useState(''),[status,setStatus]=useState('불러오는 중…'),[busy,setBusy]=useState(false),[adding,setAdding]=useState(false),[name,setName]=useState(''),[tags,setTags]=useState(''),[files,setFiles]=useState<File[]>([]);
  useEffect(()=>{const q=new URLSearchParams(location.search);void Promise.all([api<LibraryAsset[]>('asset-library'),q.get('project')?api<StoredProject>('projects/'+q.get('project')):Promise.resolve(null)]).then(([list,record])=>{setAssets(list);setProject(record);const t=q.get('target')??'';setTarget(t);const match=list.find(a=>a.url===t);if(match)setKind(match.kind);setStatus('');}).catch(e=>setStatus(String(e)));},[]);
  useEffect(()=>setLimit(120),[kind,scope,query]);
  const bindings=parseAssetBindings(project?.project.assetBindings);
  const compatible=assets.filter(a=>a.kind===kind);
  const scoped=compatible.filter(a=>scope==='all'||(scope==='used'?Object.values(bindings).includes(a.url):scope==='base'?!a.sourceProject:a.sourceProject===scope));
  const visible=scoped.filter(a=>(a.name+' '+(a.tags??'')).toLowerCase().includes(query.toLowerCase()));
  async function save(remove=false){
    if(!project||!target||(!selected&&!remove))return;
    const original=assets.find(a=>a.url===target);
    if(!remove && !!original?.files !== !!selected?.files){setStatus('단일 이미지와 동작 묶음은 서로 교체할 수 없습니다. 같은 형식의 에셋을 선택하세요.');return;}
    if(!remove && original?.files?.some(f=>!selected?.files?.includes(f))){setStatus('스킨에 필요한 방향·동작 프레임이 빠져 있습니다. 원본과 같은 파일 이름을 모두 추가해 주세요.');return;}
    if(!remove && original?.kind!==selected?.kind){setStatus('같은 종류의 에셋을 선택하세요.');return;}
    setBusy(true);try{const next={...bindings};if(remove)delete next[target];else next[target]=selected!.url;const record=await api<StoredProject>('projects/'+project.id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({baseRevision:project.revision,project:{...project.project,assetBindings:next}})});setProject(record);setStatus(remove?'이 프로젝트의 원본 에셋으로 되돌렸습니다.':'이 프로젝트에 연결했습니다. 다른 프로젝트와 공용 원본은 유지됩니다.');}catch(e){setStatus(String(e));}finally{setBusy(false);}
  }
  async function upload(){setBusy(true);try{const form=new FormData();form.set('name',name);form.set('kind',kind);form.set('tags',tags);if(project){form.set('project',project.id);form.set('projectName',String(project.project.name));}files.forEach(f=>form.append('files',f));const asset=await api<LibraryAsset>('asset-library',{method:'POST',body:form});setAssets(a=>[asset,...a]);setSelected(asset);setAdding(false);setFiles([]);setName('');setStatus('공용 에셋에 추가했습니다. 원하는 프로젝트에 연결해 주세요.');}catch(e){setStatus(String(e));}finally{setBusy(false);}}
  return <main className="asset-library"><header><a href={'/studio'+(project?'?project='+project.id+'&assetReturn=1':'')}>← 저작도구로</a><div><h1>공용 에셋</h1><p>모든 프로젝트·MOD에서 함께 쓰는 라이브러리</p></div><button onClick={()=>setAdding(!adding)}>＋ 에셋 추가</button></header>
    <div className="asset-layout"><aside><h3>에셋 종류</h3>{Object.entries(kinds).map(([key,label])=><button key={key} aria-pressed={kind===key} onClick={()=>{setKind(key);setSelected(null);setTarget('');setQuery('');}}>{label}<small>{assets.filter(a=>a.kind===key).length}</small></button>)}<p>{project?`연결할 프로젝트: ${project.project.name}`:'프로젝트 없이도 에셋을 추가하고 둘러볼 수 있습니다.'}</p></aside>
    <section><div className="asset-filters"><select aria-label="프로젝트별 에셋 필터" value={scope} onChange={e=>setScope(e.target.value)}><option value="all">전체 공용 에셋</option><option value="base">기본 제공 에셋</option>{project&&<option value="used">현재 프로젝트에 연결한 에셋</option>}{Array.from(new Map(assets.filter(a=>a.sourceProject).map(a=>[a.sourceProject!,a.sourceName||a.sourceProject!])).entries()).map(([id,label])=><option key={id} value={id}>{label}에서 추가</option>)}</select><input aria-label="에셋 검색" placeholder="이름·태그로 검색" value={query} onChange={e=>setQuery(e.target.value)}/></div><p role="status">{status}</p>
    {adding&&<fieldset><legend>새 {kinds[kind]} 추가</legend><label>이름<input value={name} onChange={e=>setName(e.target.value)}/></label><label>태그<input placeholder="트로이, 아킬레우스, 평상복…" value={tags} onChange={e=>setTags(e.target.value)}/></label><input aria-label="에셋 파일" type="file" multiple={['sprites','motions'].includes(kind)} accept={kind==='bgm'||kind==='sfx'?'.mp3,.wav,.ogg,.m4a,.webm':'.webp,.png,.jpg,.jpeg'} onChange={e=>setFiles(Array.from(e.target.files??[]))}/><p>{['sprites','motions'].includes(kind)?'동작·방향별 WebP 파일을 함께 선택하세요. 기존 스킨과 같은 프레임 이름을 사용합니다.':'기존 파일을 덮어쓰지 않고 새 에셋으로 추가합니다.'}</p><button disabled={busy||!name.trim()||!files.length} onClick={()=>void upload()}>라이브러리에 추가</button></fieldset>}
    <div className="asset-grid">{visible.slice(0,limit).map(a=><button key={a.id} aria-pressed={selected?.id===a.id} onClick={()=>setSelected(a)}>{a.kind==='bgm'||a.kind==='sfx'?<span className="audio-icon">♫</span>:<img loading="lazy" src={url(a.preview)} alt=""/>}<strong>{a.name}</strong><small>{a.sourceName||'기본 제공'} · {a.tags||kinds[a.kind]}{a.files?` · ${a.files.length} 프레임`:''}</small></button>)}</div>{visible.length>limit&&<button onClick={()=>setLimit(n=>n+120)}>더 보기 ({limit}/{visible.length})</button>}{!visible.length&&<p>에셋이 없습니다. 파일을 추가해 주세요.</p>}</section>
    <aside className="asset-detail">{selected?<><h2>{selected.name}</h2><Preview asset={selected}/><p>{selected.tags}</p>{selected.files&&<details><summary>동작·방향 파일 {selected.files.length}개</summary>{selected.files.map(f=><div key={f}>{f}</div>)}</details>}<a href={url(selected.preview)} target="_blank" rel="noreferrer">원본 보기</a></>:<p>에셋을 선택하면 크게 볼 수 있습니다.</p>}
    {project&&<fieldset><legend>이 프로젝트에 사용</legend><label>교체할 현재 에셋<select aria-label="교체할 에셋" value={target} onChange={e=>setTarget(e.target.value)}><option value="">현재 사용 슬롯 선택</option>{compatible.filter(a=>!a.url.startsWith('/assets/library/')).map(a=><option key={a.id} value={a.url}>{a.name}</option>)}</select></label><p>{bindings[target]?'다른 에셋에 연결됨':'원본 사용 중'}</p>{kind==='fx'&&<p>효과 시트는 원본과 같은 프레임 수와 칸 배치를 사용하세요.</p>}<button disabled={busy||!target||!selected} onClick={()=>void save()}>선택한 에셋 사용</button><button disabled={busy||!bindings[target]} onClick={()=>void save(true)}>원본으로 되돌리기</button><p>같은 슬롯을 사용하는 장면에 반영됩니다. 원본과 다른 프로젝트는 바뀌지 않습니다.</p></fieldset>}
    </aside></div></main>;
}
