"use client";
import {useEffect,useState} from 'react';
const poses={idle:'대기',move:'이동',attack:'공격'};
function PoseImage({src,alt}:{src:string;alt:string}) {
  const [missing,setMissing]=useState(false);
  return missing?<span className="missing-pose">이미지 없음</span>:<img src={src} alt={alt} onError={()=>setMissing(true)}/>;
}
export default function BattleSprites({commander,onDirty,classId}:{commander:string;classId:string;onDirty:(dirty:boolean)=>void}) {
  const [tier,setTier]=useState(1);
  const [base,setBase]=useState(''),[pose,setPose]=useState('idle'),[direction,setDirection]=useState('front'),[version,setVersion]=useState(0),[pending,setPending]=useState<Blob>(),[preview,setPreview]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{let live=true;setBase('');setPending(undefined);setPreview('');setStatus('이미지를 찾는 중…');
    void fetch('/api/studio/legacy/sprite-preview?'+new URLSearchParams({commander,class:classId,side:'player'})).then(r=>r.json()).then(async(urls:string[])=>{for(const url of urls){try{await new Promise<void>((resolve,reject)=>{const i=new Image();i.onload=()=>resolve();i.onerror=reject;i.src=url;});if(live){setBase(url.replace(/front_idle.webp$/,''));setStatus('게임에서 사용하는 전투 이미지입니다.');}return;}catch{}}if(live)setStatus('등록된 전투 이미지를 찾지 못했습니다.');}).catch(()=>{if(live)setStatus('이미지 목록을 불러오지 못했습니다.');});return()=>{live=false;};
  },[commander,classId]);
  const change=()=>{if(busy)return false;if(pending&&!confirm('적용하지 않은 이미지 미리보기를 버릴까요?'))return false;setPending(undefined);onDirty(false);setPreview('');return true;};
  const tierBase=base+(tier===1?'':`t${tier}/`);
  const path=tierBase+direction+'_'+pose+'.webp';
  return <section className="battle-sprite-workspace"><div className="tier-tabs" role="group" aria-label="병종 승급 단계">{[1,2,3].map(value=><button key={value} disabled={busy} aria-pressed={tier===value} className={tier===value?'active':''} onClick={()=>{if(change()){setTier(value);setStatus(`${value}단계 이미지를 편집합니다.`);}}}>{value}단계{value===1?' · 기본':''}</button>)}</div><p>선택한 단계의 이미지만 교체합니다. 이미지가 없는 동작은 게임에서 기본 이미지로 대체될 수 있습니다.</p><div className="direction-tabs">{Object.entries(poses).map(([key,label])=><button key={key} className={pose===key?'active':''} onClick={()=>{if(change())setPose(key);}}>{label}</button>)}{[['front','정면·측면'],['back','뒷모습']].map(([key,label])=><button key={key} className={direction===key?'active':''} onClick={()=>{if(change())setDirection(key!);}}>{label}</button>)}</div>
    {base&&<div className="sprite-gallery">{['front','back'].flatMap(d=>Object.entries(poses).map(([p,label])=><button key={d+p} className={direction===d&&pose===p?'active':''} onClick={()=>{if(change()){setDirection(d);setPose(p);}}}><PoseImage key={`${tierBase}${d}_${p}-${version}`} src={`${tierBase}${d}_${p}.webp?v=${version}`} alt={`${tier}단계 ${d==='front'?'정면':'뒷모습'} ${label}`}/><span>{d==='front'?'정면':'뒷모습'} · {label}</span></button>))}</div>}<div className="unregistered"><h2>{commander} · {tier}단계 전투 캐릭터</h2>{base&&<PoseImage key={preview||path+version} src={preview||path+'?v='+version} alt={`${commander} ${tier}단계 ${poses[pose as keyof typeof poses]}`}/>}</div>
    <label>이미지 교체 <input disabled={!base||busy} type="file" accept="image/png,image/webp,image/jpeg" onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;if(file.size>20000000){setStatus('20MB 이하의 이미지를 선택하세요.');return;}setBusy(true);const url=URL.createObjectURL(file);try{const img=new Image();await new Promise<void>((resolve,reject)=>{img.onload=()=>resolve();img.onerror=reject;img.src=url;});if(img.width*img.height>40000000)throw new Error('이미지가 너무 큽니다.');const c=document.createElement('canvas');c.width=img.width;c.height=img.height;c.getContext('2d')!.drawImage(img,0,0);const blob=await new Promise<Blob|null>(r=>c.toBlob(r,'image/webp',.95));if(!blob)throw new Error('이미지 변환 실패');setPending(blob);onDirty(true);setPreview(c.toDataURL('image/webp',.95));setStatus('교체할 이미지 미리보기입니다. 적용 버튼을 누르면 전투 이미지가 바뀝니다.');}catch(err){setStatus(String(err));}finally{URL.revokeObjectURL(url);setBusy(false);}}}/></label>
    <button disabled={!pending||busy} onClick={async()=>{if(!pending)return;setBusy(true);try{const id=decodeURIComponent(new URL(path,location.origin).pathname.split('/sprites/')[1]!.replace(/\.webp$/,''));const response=await fetch('/api/studio/asset-image?'+new URLSearchParams({kind:'sprites',id}),{method:'POST',body:pending});const data=await response.json();if(!response.ok)throw new Error(data.error);setVersion(Date.now());setPending(undefined);onDirty(false);setPreview('');setStatus(`${tier}단계 전투 이미지에 적용했습니다. 기존 파일은 백업했습니다.`);}catch(err){setStatus(String(err));}finally{setBusy(false);}}}>전투 이미지에 적용</button><button disabled={!pending||busy} onClick={()=>{setPending(undefined);setPreview('');onDirty(false);setStatus('미리보기를 취소했습니다.');}}>미리보기 취소</button><p role="status">{status}</p><p>같은 이미지를 사용하는 전투에 공통 적용됩니다. 좌우 반전과 피격 연출은 게임에서 처리합니다. 시나리오용 도보 동작은 별도로 유지됩니다.</p></section>;
}
